<a href="https://colab.research.google.com/github/Aashishgopal/ai_club/blob/main/numpy/NumpyTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***NUMPY IN DIFFERENT WAYS***

In [1]:
import numpy as np

**lists**

In [2]:
PythonList = [6,3,4,2]
print(PythonList)


[6, 3, 4, 2]


**NUMPY**

In [3]:
numpy_array = np.array(PythonList)
numpy_array

array([6, 3, 4, 2])

In [4]:
a = numpy_array+10
print(a)

[16 13 14 12]


In [5]:
a = np.array([1,5,9])
print(a)

[1 5 9]


In [6]:
b = a +10
print(b)

[11 15 19]


In [7]:
print(a.shape)
print(a.dtype)

(3,)
int64


In [8]:
c = np.array([(2,4,8,5),
              (3,5,7,1)])
print(c)

[[2 4 8 5]
 [3 5 7 1]]


In [9]:
d = np.array([
    [[5, 6,3],
        [8, 5, 3]],
      [[6, 8,6],
        [15, 16, 16]]
])
print(d.shape)

(2, 2, 3)


**TO PRINT 3 ROWS 3 COULMNS OF ZEROS**

In [10]:
x=np.zeros((5,5), dtype=np.int16)
print(x)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


**TO PRINT 3 TIMES OF 2 ROWS 4 COLUMNS OF ONES**

In [12]:
y=np.ones((5,2,7), dtype=np.int16)
print(y)

[[[1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1]]]


**RESHAPE TO 1 ELEMENT LISTS**

In [20]:
e  = np.array([(8,2,6), (4,3,9)])
print(e)
e.reshape(6,1)

[[8 2 6]
 [4 3 9]]


array([[8],
       [2],
       [6],
       [4],
       [3],
       [9]])

In [21]:
print(e)

[[8 2 6]
 [4 3 9]]


In [22]:
print('First row:', e[0])
print('Second row:', e[1])

First row: [8 2 6]
Second row: [4 3 9]


In [23]:
print('Second column:', e[:,1])

Second column: [2 3]


In [24]:
print(e[1, :2])

[4 3]


In [25]:
e.flatten()

array([8, 2, 6, 4, 3, 9])

**HORITONTAL AND VERTICAL STACK**

In [26]:
f = np.array([1,5,8])
g = np.array([4,9,2])

print('Horizontal Append:', np.hstack((f, g)))
print("Vertical append:")
print(np.vstack((f,g)))

Horizontal Append: [1 5 8 4 9 2]
Vertical append:
[[1 5 8]
 [4 9 2]]


**TO FIND A LIST OF RANDOM ELEMENTS**

In [27]:
normal_array = np.random.normal(4, 0.7, 10)
print(normal_array)

[4.47397994 4.79684124 3.60131042 4.44365302 3.68191163 4.46995629
 4.22255617 3.93781906 5.18154617 3.14055461]


**FIND MIN , MAX, MEAN, MEDIAN,STD FROM A LISTS**

In [28]:
print(np.min(normal_array))
print(np.max(normal_array))
print(np.mean(normal_array))
print(np.median(normal_array))
print(np.std(normal_array))

3.1405546128008153
5.181546167139519
4.195012855448136
4.333104594789818
0.5783795259391313


**TO PRINT ELEMENTS IN RANGE**

In [29]:
np.arange(1, 9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
np.arange(1, 5,9)

array([1])

In [32]:
np.linspace(1.0, 10.0, num=10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [33]:
np.linspace(1.0, 6.0, num=5, endpoint=False)

array([1., 2., 3., 4., 5.])

In [34]:
np.logspace(5.0, 4.0, num=4)

array([100000.        ,  46415.88833613,  21544.34690032,  10000.        ])

In [35]:
x = np.array([1,2,4], dtype=np.complex128)
x.itemsize

16

**TO FIND DOT PRODUCT OF MATRIX**

In [37]:
f = np.array([1,5,3])
g = np.array([4,2,7])
### 1*4+2*5+3*1
np.dot(f, g)

35

**TO FIND THE INVERSE OF MATRIX**

In [38]:
A = np.array([[5, 1, 2],
              [4, -2, 9],
              [5, 8, 9]])
  
# Calculating the inverse of the matrix
print(np.linalg.inv(A))

[[ 0.25210084 -0.01960784 -0.03641457]
 [-0.02521008 -0.09803922  0.10364146]
 [-0.11764706  0.09803922  0.03921569]]


**TO FIND THE MATRIX MULTIPLICATION**

In [39]:
h = [[1,6],[9,4]] 
i = [[5,6],[7,4]] 
### 1*5+2*7 = 19
np.matmul(h, i)

array([[47, 30],
       [73, 70]])

**TO FIND THE DETERMINANT OF MATRIX**

In [40]:
n_array = np.array([[40, 29], [20, 14]])
  
# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
  
# calculating the determinant of matrix
det = np.linalg.det(n_array)
  
print("\nDeterminant of given 2X2 matrix:")
print(int(det))

Numpy Matrix is:
[[40 29]
 [20 14]]

Determinant of given 2X2 matrix:
-19


**TO FIND THE RANK OF MATRIX**

In [41]:
mx = np.array([[1,1,2],[2,1,7],[1,5,3]])

# Let's get rank of matrix 
np.linalg.matrix_rank(mx)

3

**TO FIND THE TRANSPOSE OF THE MATRIX**

In [42]:
gfg = np.matrix('[3, 1; 15, 4]')
              
# applying matrix.transpose() method
trans = gfg.transpose()
    
print(trans)

[[ 3 15]
 [ 1  4]]


**TO FIND THE TRACE OF MATRIX**

In [43]:
gfg = np.matrix('[2, 1; 16, 5]')
              
# applying matrix.trace() method
tracem = gfg.trace()
    
print(tracem)

[[7]]


**TO FIND THE EIGEN VALUES AND EIGEN VECTORS OF MATRIX**

In [44]:
example_matrix = np.array([
  [1,5,3,7],
  [5,6,1,8],
  [9,10,8,12],
  [13,11,15,17]
])
eigenvalues, eigenvectors = np.linalg.eig(example_matrix)
print(eigenvalues, eigenvectors)

[35.13486387+0.j         -3.22997218+0.j          0.04755416+2.53928162j
  0.04755416-2.53928162j] [[-0.24375044+0.j          0.9036254 +0.j          0.07398851+0.12687077j
   0.07398851-0.12687077j]
 [-0.2714656 +0.j         -0.19095706+0.j          0.67833724+0.j
   0.67833724-0.j        ]
 [-0.52187961+0.j         -0.21476526+0.j          0.03408369-0.41650749j
   0.03408369+0.41650749j]
 [-0.77106019+0.j         -0.31760418+0.j         -0.55522399+0.18808037j
  -0.55522399-0.18808037j]]
